;;; mai-theme.el --- Microsoft AI warm-paper theme -*- lexical-binding: t; no-byte-compile: t; -*-

(deftheme mai
  "A warm-paper, dark-ink theme inspired by microsoft.ai.")

(let ((bg "#FBF0DC")
      (bg-soft "#FEF9ED")
      (bg-panel "#F7ECD9")
      (bg-muted "#EDE1C7")
      (bg-select "#D8C8A8")
      (fg "#1F1412")
      (fg-soft "#3D332E")
      (muted "#51453E")
      (subtle "#8D7F70")
      (accent "#946A3A")
      (accent-soft "#A67C52")
      (red "#74312B")
      (green "#435B31")
      (yellow "#744D27")
      (blue "#284867")
      (purple "#604159")
      (cyan "#3D625D")
      (white "#FFFFFF"))
  (custom-theme-set-faces
   'mai

   `(default ((t (:foreground ,fg :background ,bg))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:foreground ,subtle :background ,bg))))
   `(highlight ((t (:background ,bg-panel))))
   `(hl-line ((t (:background ,bg-panel))))
   `(region ((t (:background ,bg-select))))
   `(secondary-selection ((t (:background ,bg-muted))))
   `(minibuffer-prompt ((t (:foreground ,accent :weight bold))))
   `(vertical-border ((t (:foreground ,bg-select))))
   `(window-divider ((t (:foreground ,bg-select))))
   `(window-divider-first-pixel ((t (:foreground ,bg-select))))
   `(window-divider-last-pixel ((t (:foreground ,bg-select))))
   `(link ((t (:foreground ,blue :underline t))))
   `(link-visited ((t (:foreground ,purple :underline t))))
   `(shadow ((t (:foreground ,subtle))))
   `(success ((t (:foreground ,green :weight bold))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(error ((t (:foreground ,red :weight bold))))
   `(escape-glyph ((t (:foreground ,accent :weight bold))))
   `(trailing-whitespace ((t (:background ,red))))
   `(show-paren-match ((t (:foreground ,fg :background ,bg-select :weight bold))))
   `(show-paren-mismatch ((t (:foreground ,bg-soft :background ,red :weight bold))))

   `(font-lock-builtin-face ((t (:foreground ,purple))))
   `(font-lock-comment-face ((t (:foreground ,subtle :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,subtle :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,accent))))
   `(font-lock-doc-face ((t (:foreground ,subtle :slant italic))))
   `(font-lock-function-name-face ((t (:foreground ,blue :weight bold))))
   `(font-lock-keyword-face ((t (:foreground ,purple :weight bold))))
   `(font-lock-negation-char-face ((t (:foreground ,red :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,accent))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,accent :weight bold))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,purple :weight bold))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,cyan :weight bold))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-warning-face ((t (:foreground ,yellow :weight bold))))

   `(line-number ((t (:foreground ,subtle :background ,bg))))
   `(line-number-current-line ((t (:foreground ,fg :background ,bg-panel :weight bold))))
   `(isearch ((t (:foreground ,bg-soft :background ,accent :weight bold))))
   `(lazy-highlight ((t (:foreground ,fg :background "#E0C082"))))
   `(match ((t (:foreground ,fg :background "#E0C082" :weight bold))))

   `(mode-line ((t (:foreground ,bg-soft :background ,fg :box nil :weight bold))))
   `(mode-line-inactive ((t (:foreground ,muted :background ,bg-muted :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,bg-soft :weight bold))))
   `(header-line ((t (:foreground ,fg-soft :background ,bg-panel :box nil))))

   `(completions-common-part ((t (:foreground ,accent :weight bold))))
   `(completions-first-difference ((t (:foreground ,blue :weight bold))))
   `(tooltip ((t (:foreground ,fg :background ,bg-panel))))
   `(child-frame-border ((t (:background ,accent))))

   `(company-tooltip ((t (:foreground ,fg :background ,bg-panel))))
   `(company-tooltip-selection ((t (:foreground ,fg :background ,bg-select))))
   `(company-tooltip-common ((t (:foreground ,accent :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,subtle))))
   `(company-scrollbar-bg ((t (:background ,bg-muted))))
   `(company-scrollbar-fg ((t (:background ,accent))))

   `(corfu-default ((t (:foreground ,fg :background ,bg-panel))))
   `(corfu-current ((t (:foreground ,fg :background ,bg-select))))
   `(corfu-bar ((t (:background ,accent))))
   `(orderless-match-face-0 ((t (:foreground ,accent :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,blue :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,green :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,purple :weight bold))))

   `(vertico-current ((t (:foreground ,fg :background ,bg-select))))
   `(marginalia-date ((t (:foreground ,accent))))
   `(marginalia-documentation ((t (:foreground ,subtle :slant italic))))
   `(marginalia-file-name ((t (:foreground ,fg))))
   `(marginalia-key ((t (:foreground ,accent))))
   `(marginalia-size ((t (:foreground ,subtle))))
   `(consult-highlight-match ((t (:foreground ,accent :weight bold))))
   `(consult-preview-match ((t (:background "#E0C082" :foreground ,fg))))

   `(doom-modeline-bar ((t (:background ,accent))))
   `(doom-modeline-buffer-file ((t (:foreground ,bg-soft :weight bold))))
   `(doom-modeline-buffer-major-mode ((t (:foreground ,accent-soft :weight bold))))
   `(doom-modeline-info ((t (:foreground ,blue))))
   `(doom-modeline-warning ((t (:foreground ,yellow))))
   `(doom-modeline-error ((t (:foreground ,red))))
   `(doom-dashboard-banner ((t (:foreground ,accent))))
   `(doom-dashboard-menu-title ((t (:foreground ,fg :weight bold))))
   `(doom-dashboard-menu-desc ((t (:foreground ,muted))))
   `(doom-dashboard-footer ((t (:foreground ,subtle))))

   `(which-key-key-face ((t (:foreground ,accent :weight bold))))
   `(which-key-command-description-face ((t (:foreground ,fg))))
   `(which-key-group-description-face ((t (:foreground ,blue))))
   `(which-key-separator-face ((t (:foreground ,subtle))))
   `(which-key-local-map-description-face ((t (:foreground ,purple))))

   `(dired-directory ((t (:foreground ,blue :weight bold))))
   `(dired-flagged ((t (:foreground ,red :weight bold))))
   `(dired-marked ((t (:foreground ,accent :weight bold))))
   `(dired-symlink ((t (:foreground ,cyan :weight bold))))
   `(dired-warning ((t (:foreground ,yellow :weight bold))))

   `(diff-added ((t (:foreground ,green :background "#E5E8C8"))))
   `(diff-changed ((t (:foreground ,yellow :background ,bg-muted))))
   `(diff-removed ((t (:foreground ,red :background "#E8CFC7"))))
   `(diff-refine-added ((t (:foreground ,fg :background "#D5DEAD" :weight bold))))
   `(diff-refine-changed ((t (:foreground ,fg :background "#E0C082" :weight bold))))
   `(diff-refine-removed ((t (:foreground ,fg :background "#D8A9A0" :weight bold))))
   `(ediff-current-diff-A ((t (:background "#E8CFC7"))))
   `(ediff-current-diff-B ((t (:background "#E5E8C8"))))
   `(ediff-current-diff-C ((t (:background ,bg-muted))))
   `(ediff-fine-diff-A ((t (:background "#D8A9A0" :weight bold))))
   `(ediff-fine-diff-B ((t (:background "#D5DEAD" :weight bold))))
   `(ediff-fine-diff-C ((t (:background "#E0C082" :weight bold))))

   `(magit-section-heading ((t (:foreground ,accent :weight bold))))
   `(magit-section-highlight ((t (:background ,bg-panel))))
   `(magit-branch-local ((t (:foreground ,blue :weight bold))))
   `(magit-branch-remote ((t (:foreground ,green :weight bold))))
   `(magit-hash ((t (:foreground ,subtle))))
   `(magit-diff-added ((t (:foreground ,green :background "#E5E8C8"))))
   `(magit-diff-added-highlight ((t (:foreground ,green :background "#DDE4BD" :weight bold))))
   `(magit-diff-removed ((t (:foreground ,red :background "#E8CFC7"))))
   `(magit-diff-removed-highlight ((t (:foreground ,red :background "#E0BEB6" :weight bold))))
   `(magit-diff-context ((t (:foreground ,fg-soft :background ,bg))))
   `(magit-diff-context-highlight ((t (:foreground ,fg :background ,bg-panel))))
   `(magit-diff-file-heading ((t (:foreground ,fg :weight bold))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg-panel :weight bold))))
   `(magit-diff-hunk-heading ((t (:foreground ,muted :background ,bg-muted))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,fg :background ,bg-select))))

   `(flycheck-error ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flycheck-info ((t (:underline (:style wave :color ,blue)))))
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flymake-note ((t (:underline (:style wave :color ,blue)))))

   `(org-level-1 ((t (:foreground ,fg :weight bold :height 1.25))))
   `(org-level-2 ((t (:foreground ,blue :weight bold :height 1.15))))
   `(org-level-3 ((t (:foreground ,green :weight bold :height 1.08))))
   `(org-level-4 ((t (:foreground ,accent :weight bold))))
   `(org-level-5 ((t (:foreground ,purple :weight bold))))
   `(org-level-6 ((t (:foreground ,cyan :weight bold))))
   `(org-document-title ((t (:foreground ,fg :weight bold :height 1.35))))
   `(org-document-info ((t (:foreground ,muted))))
   `(org-block ((t (:foreground ,fg-soft :background ,bg-panel))))
   `(org-block-begin-line ((t (:foreground ,subtle :background ,bg-muted))))
   `(org-block-end-line ((t (:foreground ,subtle :background ,bg-muted))))
   `(org-code ((t (:foreground ,accent))))
   `(org-verbatim ((t (:foreground ,green))))
   `(org-table ((t (:foreground ,blue))))
   `(org-date ((t (:foreground ,accent :underline t))))
   `(org-done ((t (:foreground ,green :weight bold))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-headline-done ((t (:foreground ,subtle :strike-through t))))
   `(org-checkbox ((t (:foreground ,accent :weight bold))))
   `(org-special-keyword ((t (:foreground ,subtle))))
   `(org-meta-line ((t (:foreground ,subtle :slant italic))))
   `(org-ellipsis ((t (:foreground ,accent))))
   `(org-modern-label ((t (:foreground ,fg :background ,bg-muted))))

   `(markdown-header-face-1 ((t (:foreground ,fg :weight bold :height 1.3))))
   `(markdown-header-face-2 ((t (:foreground ,blue :weight bold :height 1.2))))
   `(markdown-header-face-3 ((t (:foreground ,green :weight bold :height 1.12))))
   `(markdown-header-face-4 ((t (:foreground ,accent :weight bold))))
   `(markdown-header-face-5 ((t (:foreground ,purple :weight bold))))
   `(markdown-header-face-6 ((t (:foreground ,cyan :weight bold))))
   `(markdown-code-face ((t (:foreground ,fg-soft :background ,bg-panel))))
   `(markdown-inline-code-face ((t (:foreground ,accent :background ,bg-panel))))
   `(markdown-blockquote-face ((t (:foreground ,muted :slant italic))))
   `(markdown-link-face ((t (:foreground ,blue :underline t))))
   `(markdown-url-face ((t (:foreground ,subtle))))

   `(tree-sitter-hl-face:comment ((t (:foreground ,subtle :slant italic))))
   `(tree-sitter-hl-face:string ((t (:foreground ,green))))
   `(tree-sitter-hl-face:keyword ((t (:foreground ,purple :weight bold))))
   `(tree-sitter-hl-face:function ((t (:foreground ,blue :weight bold))))
   `(tree-sitter-hl-face:type ((t (:foreground ,cyan :weight bold))))
   `(tree-sitter-hl-face:variable ((t (:foreground ,fg))))
   `(tree-sitter-hl-face:constant ((t (:foreground ,accent))))
   `(tree-sitter-hl-face:property ((t (:foreground ,blue))))

   `(treemacs-root-face ((t (:foreground ,fg :weight bold :height 1.1))))
   `(treemacs-directory-face ((t (:foreground ,blue))))
   `(treemacs-file-face ((t (:foreground ,fg-soft))))
   `(treemacs-git-added-face ((t (:foreground ,green))))
   `(treemacs-git-modified-face ((t (:foreground ,yellow))))
   `(treemacs-git-untracked-face ((t (:foreground ,accent))))
   `(treemacs-git-renamed-face ((t (:foreground ,cyan))))
   `(treemacs-git-conflict-face ((t (:foreground ,red :weight bold))))

   `(vterm-color-black ((t (:foreground "#140C0A" :background "#140C0A"))))
   `(vterm-color-red ((t (:foreground ,red :background ,red))))
   `(vterm-color-green ((t (:foreground ,green :background ,green))))
   `(vterm-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(vterm-color-blue ((t (:foreground ,blue :background ,blue))))
   `(vterm-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(vterm-color-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(vterm-color-white ((t (:foreground ,muted :background ,bg-muted)))))

  (custom-theme-set-variables
   'mai
   `(ansi-color-names-vector [,fg ,red ,green ,yellow ,blue ,purple ,cyan ,muted])
   `(frame-background-mode 'light)))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path (file-name-directory load-file-name)))

(provide-theme 'mai)

;;; mai-theme.el ends here
